# Generated by Django 4.2.6 on 2023-10-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerNumber',
            field=models.IntegerField(),
        ),
    ]
