# Generated by Django 4.2.6 on 2023-11-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_alter_customer_customernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('address_number', models.IntegerField()),
                ('address_box', models.CharField(max_length=30)),
                ('address_complement', models.CharField(max_length=30)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Address_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('vat_number', models.CharField(max_length=30)),
                ('phone_number_general', models.CharField(max_length=20)),
                ('mail_general', models.EmailField(max_length=50)),
                ('bank_name', models.CharField(max_length=40)),
                ('bank_iban', models.CharField(max_length=40)),
                ('bank_bic', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('client', models.CharField(max_length=40)),
                ('phone_number_private', models.CharField(max_length=20)),
                ('mail_private', models.EmailField(max_length=50)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40)),
                ('iso_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount_exc_vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount_vat', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_term', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_term_code', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_number', models.CharField(max_length=30)),
                ('supplier_name', models.CharField(max_length=30)),
                ('vat_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vat_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerNumber',
            new_name='customer_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='faxNumber',
            new_name='fax_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='registeredVat',
            new_name='registered_vat',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='vatNumber',
            new_name='vat_number',
        ),
        migrations.CreateModel(
            name='Vat_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.country')),
                ('vat_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.vat_type')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('supplier_number', models.IntegerField()),
                ('barcode', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.supplier')),
                ('vat_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.vat_type')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.invoice')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.item')),
                ('vat_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.vat_type')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.customer'),
        ),
        migrations.CreateModel(
            name='Contact_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_pro', models.CharField(max_length=20)),
                ('mail_pro', models.EmailField(max_length=50)),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.contact')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_pro', models.CharField(max_length=20)),
                ('mail_pro', models.EmailField(max_length=50)),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.contact')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Companie_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_pro', models.CharField(max_length=20)),
                ('mail_pro', models.EmailField(max_length=50)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.companie')),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.contact')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('zip_code', models.IntegerField()),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Address_Address_Type_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.address')),
                ('address_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.address_types')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Address_Address_Type_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.address')),
                ('address_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.address_types')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Address_Address_Type_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.address')),
                ('address_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.address_types')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.companie')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_term_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.payment_terms'),
        ),
    ]
