# Generated by Django 4.2.6 on 2024-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_address_address_types_category_companie_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vat_type',
            name='vat_type',
        ),
        migrations.AddField(
            model_name='vat_type',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
