# Generated by Django 4.2.6 on 2024-01-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_alter_item_supplier_id_alter_item_vat_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(max_length=40),
        ),
    ]
