# Generated by Django 4.2.6 on 2024-01-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_alter_city_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_terms',
            name='payment_term',
            field=models.CharField(max_length=40),
        ),
    ]
