# Generated by Django 4.2.6 on 2024-01-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_alter_payment_terms_payment_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=20),
        ),
    ]
