# Generated by Django 4.2.6 on 2024-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0008_alter_customer_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vat_type',
            name='vat_percentage',
        ),
        migrations.AddField(
            model_name='vat_type',
            name='vat_type',
            field=models.CharField(default='Exempte de TVA', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
