# Generated by Django 4.2.6 on 2024-01-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0010_alter_vat_type_vat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat_type',
            name='vat_type',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
