# Generated by Django 4.2.6 on 2024-01-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0011_alter_vat_type_vat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='communication',
            field=models.TextField(default='Aucune'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='flag_accounting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='vat_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
