# Generated by Django 4.2.6 on 2024-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0013_alter_invoice_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
