# Generated by Django 4.2.6 on 2024-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0014_alter_item_price_alter_item_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_description',
            field=models.CharField(max_length=100),
        ),
    ]
