# Generated by Django 4.2.6 on 2024-01-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0016_alter_item_supplier_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
