# Generated by Django 4.2.6 on 2024-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0017_alter_item_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='flag_accounting',
            field=models.CharField(max_length=20),
        ),
    ]
