# Generated by Django 4.2.6 on 2024-01-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0018_alter_invoice_flag_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=40),
        ),
    ]
