# Generated by Django 4.2.6 on 2024-01-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0019_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplier_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
