# Generated by Django 4.2.6 on 2024-04-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0021_uploadedfile_invoice_discount_total'),
    ]

    operations = [
    ]
