# Generated by Django 4.2.6 on 2024-03-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0021_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
