# Generated by Django 4.2.6 on 2024-04-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0022_auto_20240404_1101'),
        ('monApp', '0023_alter_uploadedfile_id'),
    ]

    operations = [
    ]
