# Generated by Django 4.2.6 on 2024-04-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0024_merge_20240404_1111'),
    ]

    operations = [
    ]
