# Generated by Django 4.2.6 on 2024-04-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0025_auto_20240404_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='vat_type_id',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Invoice_item',
        ),
    ]
