# Generated by Django 4.2.6 on 2024-04-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0026_remove_invoice_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount_exc_vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount_vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flag_accounting', models.CharField(max_length=20)),
                ('communication', models.TextField()),
                ('discount_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploaded_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.invoice')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.item')),
                ('vat_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.vat_type')),
            ],
        ),
    ]
