# Generated by Django 4.2.6 on 2024-04-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0027_invoice_uploadedfile_invoice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file_link',
            field=models.URLField(blank=True),
        ),
    ]
