# Generated by Django 4.2.6 on 2024-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0030_invoice_structured_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='vat_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
