# Generated by Django 4.2.6 on 2024-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0031_alter_companie_vat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='communication',
            field=models.TextField(blank=True),
        ),
    ]
