# Generated by Django 4.2.6 on 2024-05-16 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0035_invoice_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
