# Generated by Django 4.2.6 on 2024-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0036_alter_invoice_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='.'),
        ),
    ]
